import { Button, VerticalBox } from "std-widgets.slint";

component Circle inherits Rectangle {
    width: 30px;
    height: 30px;
    border-radius: root.width / 2;
    }

component Star inherits Circle {

        callback clicked <=> touch.clicked;
        background: yellow;

        label := Text {
            x: 100px; y: 100px;
            color: white;
        }
        touch := TouchArea { }

            property <bool> active: true;
            states [
                active when active && !touch.has-hover: {

                }
                active-hover when active && touch.has-hover: {
                    label.text: "Active";
                }
            ]
}

export component AppWindow inherits Window {
    width: 500px;
    height: 200px;
    background: black;

    in-out property<int> number_of_stars: 7;
    in-out property<string> message;

    callback request-description(int);
    callback leave();
    callback explore() -> string;

    VerticalBox {
        Text {
            text: root.message;
            color: white;
        }
     }

     for data in number_of_stars: Star {
        clicked => {
           root.request-description(data);
        }
        x: data * 32px; y: 40px;
     }


          leave := Button {

                  x: 0px;
                  y: 170px;

                 text: "Leave";
                 clicked => {
                     root.leave();
                 }
             }

                   explore := Button {

                               x: 400px;
                               y: 170px;

                              text: "Explore";
                              clicked => {
                                  root.explore();
                              }
                          }

}
